"""created tables theme,moodboard,branddna

Revision ID: 241128eecd5b
Revises: efd89de191bd
Create Date: 2026-03-14 16:38:40.425572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241128eecd5b'
down_revision: Union[str, None] = 'efd89de191bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_positioning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cultural_influences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('core_values_and_voice', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_reference_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('strictness', sa.Float(), nullable=True),
    sa.Column('classification_notes', sa.String(), nullable=True),
    sa.Column('brand_class', sa.String(), nullable=True),
    sa.Column('classification_reasoning', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brand_name', 'brand', ['brand_name'], unique=False)
    op.create_index('ix_brand_status', 'brand', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_req', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('range_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collections_brand_id', 'collections', ['brand_id'], unique=False)
    op.create_index('ix_collections_status', 'collections', ['status'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('theme_name', sa.String(length=255), nullable=False),
    sa.Column('theme_slug', sa.String(length=255), nullable=False),
    sa.Column('season_title', sa.String(length=100), nullable=True),
    sa.Column('main_concept', sa.Text(), nullable=True),
    sa.Column('one_line_summary', sa.String(length=500), nullable=True),
    sa.Column('mood_tags', sa.String(length=500), nullable=True),
    sa.Column('design_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aesthetic_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_aligned_to_brand_dna', sa.Boolean(), nullable=True),
    sa.Column('key_story_points', sa.Text(), nullable=True),
    sa.Column('lifestyle_context_notes', sa.Text(), nullable=True),
    sa.Column('gender_or_inclusivity_notes', sa.Text(), nullable=True),
    sa.Column('primary_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accent_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('neutral_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('palette_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('palette', sa.String(length=500), nullable=True),
    sa.Column('meaningful_color_associations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pantone_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coloro_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fabric_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trim_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('print_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('important_fabrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('important_silhouettes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_silhouettes', sa.String(length=500), nullable=True),
    sa.Column('key_trend_fabrics', sa.String(length=500), nullable=True),
    sa.Column('print_usage_guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('print_placement_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wash_and_finish_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graphic_and_icon_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typography_micro_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fit_and_proportion_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_micro_trend_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('construction_detail_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessory_and_styling_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fabric_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trim_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artwork_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_themes_collection_id', 'themes', ['collection_id'], unique=False)
    op.create_index('ix_themes_status', 'themes', ['status'], unique=False)
    op.create_index('ix_themes_theme_slug', 'themes', ['theme_slug'], unique=False)
    op.create_table('theme_moodboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('moodboard_slug', sa.String(length=255), nullable=True),
    sa.Column('collage_prompt', sa.Text(), nullable=True),
    sa.Column('collage_reference_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collage_image_url', sa.String(length=1024), nullable=True),
    sa.Column('element_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('element_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id')
    )
    op.create_index('ix_theme_moodboards_status', 'theme_moodboards', ['status'], unique=False)
    op.create_index('ix_theme_moodboards_theme_id', 'theme_moodboards', ['theme_id'], unique=False)
    op.create_table('theme_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('category_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trend_spotting', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id')
    )
    op.create_index('ix_theme_trends_status', 'theme_trends', ['status'], unique=False)
    op.create_index('ix_theme_trends_theme_id', 'theme_trends', ['theme_id'], unique=False)
    op.drop_index('ix_task_created_at', table_name='task')
    op.drop_index('ix_task_updated_at', table_name='task')
    op.drop_index('ix_thread_created_at', table_name='thread')
    op.drop_index('ix_thread_updated_at', table_name='thread')
    op.drop_index('ix_thread_message_created_at', table_name='thread_message')
    op.drop_index('ix_thread_message_updated_at', table_name='thread_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_thread_message_updated_at', 'thread_message', ['updated_at'], unique=False)
    op.create_index('ix_thread_message_created_at', 'thread_message', ['created_at'], unique=False)
    op.create_index('ix_thread_updated_at', 'thread', ['updated_at'], unique=False)
    op.create_index('ix_thread_created_at', 'thread', ['created_at'], unique=False)
    op.create_index('ix_task_updated_at', 'task', ['updated_at'], unique=False)
    op.create_index('ix_task_created_at', 'task', ['created_at'], unique=False)
    op.drop_index('ix_theme_trends_theme_id', table_name='theme_trends')
    op.drop_index('ix_theme_trends_status', table_name='theme_trends')
    op.drop_table('theme_trends')
    op.drop_index('ix_theme_moodboards_theme_id', table_name='theme_moodboards')
    op.drop_index('ix_theme_moodboards_status', table_name='theme_moodboards')
    op.drop_table('theme_moodboards')
    op.drop_index('ix_themes_theme_slug', table_name='themes')
    op.drop_index('ix_themes_status', table_name='themes')
    op.drop_index('ix_themes_collection_id', table_name='themes')
    op.drop_table('themes')
    op.drop_index('ix_collections_status', table_name='collections')
    op.drop_index('ix_collections_brand_id', table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_brand_status', table_name='brand')
    op.drop_index('ix_brand_name', table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
