"""updated collection adding moodboard image

Revision ID: 67020170f55d
Revises: d63be8bfdcce
Create Date: 2026-03-16 16:57:44.523282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67020170f55d'
down_revision: Union[str, None] = 'd63be8bfdcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_constraint('collections_brand_id_fkey', 'collections', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('collections_brand_id_fkey', 'collections', 'brand', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_column('collections', 'image_url')
    # ### end Alembic commands ###
