"""udpated new tables

Revision ID: d63be8bfdcce
Revises: 241128eecd5b
Create Date: 2026-03-16 15:26:12.010772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63be8bfdcce'
down_revision: Union[str, None] = '241128eecd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('external_job_id', sa.String(), nullable=True),
    sa.Column('external_style_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('designer_review', sa.String(), nullable=False),
    sa.Column('showroom_review', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fabric', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('garment_type', sa.String(), nullable=True),
    sa.Column('key_details', sa.Text(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_slug', sa.String(), nullable=True),
    sa.Column('fabric_composition', sa.String(), nullable=True),
    sa.Column('sheet_image', sa.String(), nullable=True),
    sa.Column('swatch_image', sa.String(), nullable=True),
    sa.Column('artwork_image', sa.String(), nullable=True),
    sa.Column('garment_image', sa.String(), nullable=True),
    sa.Column('theme_name', sa.String(), nullable=True),
    sa.Column('theme_slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_theme_styles_designer_review', 'theme_styles', ['designer_review'], unique=False)
    op.create_index('ix_theme_styles_external_job_id', 'theme_styles', ['external_job_id'], unique=False)
    op.create_index('ix_theme_styles_showroom_review', 'theme_styles', ['showroom_review'], unique=False)
    op.create_index('ix_theme_styles_status', 'theme_styles', ['status'], unique=False)
    op.create_index('ix_theme_styles_theme_id', 'theme_styles', ['theme_id'], unique=False)
    op.add_column('themes', sa.Column('review_status', sa.String(length=20), nullable=True))
    op.add_column('themes', sa.Column('review_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'review_notes')
    op.drop_column('themes', 'review_status')
    op.drop_index('ix_theme_styles_theme_id', table_name='theme_styles')
    op.drop_index('ix_theme_styles_status', table_name='theme_styles')
    op.drop_index('ix_theme_styles_showroom_review', table_name='theme_styles')
    op.drop_index('ix_theme_styles_external_job_id', table_name='theme_styles')
    op.drop_index('ix_theme_styles_designer_review', table_name='theme_styles')
    op.drop_table('theme_styles')
    # ### end Alembic commands ###
