"""threads

Revision ID: efd89de191bd
Revises: 
Create Date: 2026-03-12 17:16:50.574826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efd89de191bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_created_at'), 'thread', ['created_at'], unique=False)
    op.create_index(op.f('ix_thread_org_id'), 'thread', ['org_id'], unique=False)
    op.create_index(op.f('ix_thread_updated_at'), 'thread', ['updated_at'], unique=False)
    op.create_index(op.f('ix_thread_user_email'), 'thread', ['user_email'], unique=False)
    op.create_index(op.f('ix_thread_user_id'), 'thread', ['user_id'], unique=False)
    op.create_index('ix_thread_user_org_updated', 'thread', ['user_id', 'org_id', 'updated_at'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_thread_id'), 'task', ['thread_id'], unique=False)
    op.create_index(op.f('ix_task_updated_at'), 'task', ['updated_at'], unique=False)
    op.create_table('thread_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_uuid', sa.UUID(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role'), nullable=True),
    sa.Column('prompt_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_query', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['thread_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_uuid'], ['thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_message_created_at'), 'thread_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_thread_message_thread_uuid'), 'thread_message', ['thread_uuid'], unique=False)
    op.create_index(op.f('ix_thread_message_updated_at'), 'thread_message', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_message_updated_at'), table_name='thread_message')
    op.drop_index(op.f('ix_thread_message_thread_uuid'), table_name='thread_message')
    op.drop_index(op.f('ix_thread_message_created_at'), table_name='thread_message')
    op.drop_table('thread_message')
    op.drop_index(op.f('ix_task_updated_at'), table_name='task')
    op.drop_index(op.f('ix_task_thread_id'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    op.drop_index('ix_thread_user_org_updated', table_name='thread')
    op.drop_index(op.f('ix_thread_user_id'), table_name='thread')
    op.drop_index(op.f('ix_thread_user_email'), table_name='thread')
    op.drop_index(op.f('ix_thread_updated_at'), table_name='thread')
    op.drop_index(op.f('ix_thread_org_id'), table_name='thread')
    op.drop_index(op.f('ix_thread_created_at'), table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###
