import json
from typing import List

import httpx

from config.settings import loaded_config
from config.logging import logger

class SerpGoogleTrends:
    """
    Serp API used for fetching google trends data
    """

    def __init__(self, api_key: str | None = None):
        self.async_client = httpx.AsyncClient(
            base_url=loaded_config.serp_base_url,
            timeout=20.0,
        )

        self.base_params = {
            "engine": "google_trends",
            "api_key": api_key or loaded_config.serp_api_key
        }

    async def get_trends_by_region(self, iso_country_code: str, query: str):
        """
        Get Trends By Query and Region's ISO Code
        :param iso_country_code: Region ISO Code
        :param query: User's intended query generated by the LLM
        :return: JSON Comprising all the trends by region
        """
        params = {
            **self.base_params,
            "geo": iso_country_code,
            "q": query
        }

        response = await self.async_client.get("/", params=params)

        return response.json()


    async def get_related_queries_rising_and_current_top(self, query: str, iso_country_code: str):
        """
        Get related rising and top queries
        :param query: String generated by LLM
        :param iso_country_code: Country code for which we want those queries
        :return: JSON Comprising all the rising and top queries related to the given query
        """
        params = {
            **self.base_params,
            "geo": iso_country_code,
            "q": query,
            "hl": "en",
            "data_type": "RELATED_QUERIES"
        }

        response = await self.async_client.get("/", params=params)

        return response.json()

    async def get_interest_over_a_timeperiod(
        self,
        query: str,
        date: str | None = None,
    ):
        """
        Get interest-over-time (timeseries) for a query.
        :param query: String generated by LLM
        :param date: Optional date range (e.g., "today 3-m", "today 12-m")
        :return: JSON comprising interest-over-time timeline data
        """
        params = {
            **self.base_params,
            "q": query,
            "data_type": "TIMESERIES",
        }
        if date:
            params["date"] = date

        response = await self.async_client.get("/", params=params)

        return response.json()

    async def get_interest_over_time_with_region(
        self,
        query: str,
        iso_country_code: str | None = None,
        date: str | None = None,
    ):
        """
        Get interest-over-time (timeseries) for a query with optional region.
        This is a copy of get_interest_over_a_timeperiod with geo parameter support.
        :param query: String generated by LLM
        :param iso_country_code: Optional region ISO code (e.g., "US", "IN", "GB", "JP")
        :param date: Optional date range (e.g., "today 3-m", "today 12-m")
        :return: JSON comprising interest-over-time timeline data
        """
        response = None
        params = {
            **self.base_params,
            "q": query,
            "data_type": "TIMESERIES",
            "include_low_search_volume":True
        }
        if iso_country_code:
            params["geo"] = iso_country_code
        if date:
            params["date"] = date

        try:
            response = await self.async_client.get("/", params=params,timeout=300)
        except Exception as e:
             print(f"error - {e}",flush=True)


        logger.info(f"Response for query - {query}  ")

        return response.json()

    async def get_interest_over_time_batched(
        self,
        queries: List[str],
        iso_country_code: str | None = None,
        date: str | None = None,
    ):
        """
        Get interest-over-time (timeseries) for multiple queries in a single API call.
        
        This batched version sends up to 5 queries comma-separated to reduce API calls.
        The response includes data for all queries, with each value entry containing
        a 'query' field to identify which term it belongs to.
        
        :param queries: List of search terms (max 5 per SERP API limit)
        :param iso_country_code: Optional region ISO code (e.g., "US", "IN", "GB", "JP")
        :param date: Optional date range (e.g., "today 3-m", "today 12-m")
        :return: JSON comprising interest-over-time timeline data for all queries
        """
        response = None
        
        # Join queries with comma (SERP API format), limit to 5
        query_string = ",".join(queries[:5])
        
        params = {
            **self.base_params,
            "q": query_string,
            "data_type": "TIMESERIES",
            "include_low_search_volume": True
        }
        if iso_country_code:
            params["geo"] = iso_country_code
        if date:
            params["date"] = date

        try:
            response = await self.async_client.get("/", params=params, timeout=300)
        except Exception as e:
            logger.error(f"Error fetching batched trends for queries {queries}: {e}")
            return {}

        logger.info(f"Batched response for {len(queries)} queries in region {iso_country_code}")

        return response.json() if response else {}