from typing import Literal

from langchain.chat_models import init_chat_model
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

from config.settings import loaded_config

OPENAI_MODEL_TYPE = Literal["gpt-5.1","gpt-4.1","gpt-5.2"]


class ModelManager:

    def __init__(self, system_prompt: str | None):
        self.system_prompt = system_prompt
        self._model: BaseChatModel | None = None

    def _set_model(self, model_name: OPENAI_MODEL_TYPE, api_key: str | None = None):
        """
        Set current active model with optional API key.
        If api_key is not provided, it will attempt to use environment variables.
        """
        kwargs = {"temperature": 0, "api_key": api_key or loaded_config.openai_gpt4_key}
        self._model = init_chat_model(model_name, **kwargs)

    @property
    def model(self) -> BaseChatModel:
        """
        Get current active model
        :return:
        """
        return self._model

    @model.setter
    def model(self, model_name: OPENAI_MODEL_TYPE):
        """
        Convenience setter for model name without explicit API key.
        """
        self._set_model(model_name)


    async def get_response(self, system_prompt: str | None, user_message: str):
        """
        Get response on the basis of class level system prompt or function level
        :param system_prompt: System prompt to be provided to the LLM
        :param user_message: Message generated by our workflow or Users if used as an API
        :return: Returns the response by LLM
        """
        if self._model is None:
            raise RuntimeError("Model is not set. Set `self.model` before calling get_response.")

        final_system_prompt = system_prompt or self.system_prompt

        messages = []
        if final_system_prompt:
            messages.append(SystemMessage(content=final_system_prompt))

        messages.append(HumanMessage(content=user_message))

        ai_msg: AIMessage = await self._model.ainvoke(messages)
        return ai_msg.content




